# Generated by Django 5.1.7 on 2025-04-12 22:12

import django.db.models.deletion
import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_total_price_alter_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(default=rentals.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='rentals.location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.ForeignKey(default=rentals.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='rentals.location'),
        ),
    ]
