# Generated by Django 5.1.7 on 2025-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_location_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
