# Generated by Django 5.1.7 on 2025-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, choices=[('economy', 'Эконом'), ('compact', 'Компактный'), ('luxury', 'Люкс'), ('suv', 'Внедорожник'), ('van', 'Фургон')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Автоматическая'), ('manual', 'Механическая')], max_length=50),
        ),
    ]
