# Generated by Django 5.1.7 on 2025-04-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_car_category_alter_car_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
    ]
